# Generated by Django 4.1.3 on 2026-04-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[("employee", "Employee"), ("admin", "Admin")], max_length=50
            ),
        ),
    ]
