# Generated by Django 5.2.12 on 2026-03-31 15:39

import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, unique=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="policies/pdfs/"),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField()),
                ("deprecation_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_policy_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("meals", "Meals"),
                            ("transport", "Transport"),
                            ("lodging", "Lodging"),
                            ("entertainment", "Entertainment"),
                            ("office_supplies", "Office Supplies"),
                            ("training", "Training"),
                            ("gifts", "Gifts"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("New York", "New York"),
                            ("London", "London"),
                            ("Tokyo", "Tokyo"),
                            ("Singapore", "Singapore"),
                            ("Remote", "Remote"),
                            ("Global", "Global"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("max_amount", "Max Amount"),
                            ("per_diem", "Per Diem"),
                            ("prohibited", "Prohibited"),
                            ("requires_approval", "Requires Approval"),
                            ("conditional", "Conditional"),
                        ],
                        max_length=50,
                    ),
                ),
                ("constraint_name", models.CharField(max_length=100)),
                ("constraint_value", models.CharField(max_length=255)),
                ("constraint_metadata", models.JSONField(blank=True, null=True)),
                ("description", models.TextField()),
                ("exceptions", models.JSONField(blank=True, null=True)),
                ("referenced_page", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="policies.policydocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("indexed_content", models.TextField(blank=True)),
                (
                    "policy_rule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index",
                        to="policies.policyrule",
                    ),
                ),
            ],
        ),
    ]
