# Generated by Django 4.1.3 on 2026-04-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "policies",
            "0002_policydocument_status_alter_policydocument_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="policydocument",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
