# Generated by Django 5.2.12 on 2026-03-31 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedReceiptData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merchant_name", models.CharField(max_length=255)),
                ("transaction_date", models.DateField()),
                ("claimed_expense_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency_code",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("GBP", "GBP"),
                            ("JPY", "JPY"),
                            ("EUR", "EUR"),
                            ("SGD", "SGD"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("line_items", models.JSONField()),
                ("ocr_confidence_score", models.FloatField()),
                ("raw_ocr_text", models.TextField()),
                ("date_mismatch_flag", models.BooleanField(default=False)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("manual_corrections", models.JSONField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_category",
                    models.CharField(
                        choices=[
                            ("meals", "Meals"),
                            ("transport", "Transport"),
                            ("lodging", "Lodging"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("business_purpose", models.TextField()),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_claims",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "extracted_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="receipts.extractedreceiptdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.FileField(upload_to="receipts/originals/")),
                ("file_size", models.PositiveIntegerField()),
                ("upload_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error_message", models.TextField(blank=True, null=True)),
                ("image_quality_score", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_uploads",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="extractedreceiptdata",
            name="receipt_upload",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_data",
                to="receipts.receiptupload",
            ),
        ),
    ]
