# Generated by Django 4.1.3 on 2026-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptupload",
            name="expense_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receiptupload",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
