# Generated by Django 4.1.3 on 2026-04-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_receiptupload_expense_date_receiptupload_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptupload",
            name="file_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="receiptupload",
            name="is_potential_duplicate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receiptupload",
            name="receipt_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
