# Generated by Django 5.2.12 on 2026-03-31 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
        ("receipts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("flagged", "Flagged"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("approval_confidence_score", models.FloatField()),
                ("generated_explanation", models.TextField()),
                ("flagged_issues", models.JSONField(blank=True, null=True)),
                ("decision_made_by_system", models.BooleanField(default=True)),
                ("manually_overridden_at", models.DateTimeField(blank=True, null=True)),
                ("override_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manually_overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overridden_audit_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged"),
                            ("overridden", "Overridden"),
                            ("escalated", "Escalated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action_timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "audit_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="audit.auditdecision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_started_at", models.DateTimeField(auto_now_add=True)),
                ("audit_completed_at", models.DateTimeField(blank=True, null=True)),
                ("audit_duration_ms", models.IntegerField(blank=True, null=True)),
                ("total_rules_checked", models.IntegerField(default=0)),
                ("rules_matched", models.IntegerField(default=0)),
                ("rules_flagged", models.IntegerField(default=0)),
                (
                    "policy_version_used",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_sessions",
                        to="policies.policydocument",
                    ),
                ),
                (
                    "receipt_approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_session",
                        to="receipts.receiptapproval",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="auditdecision",
            name="audit_session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision",
                to="audit.auditsession",
            ),
        ),
    ]
