# Generated by Django 4.1.3 on 2026-04-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_preauthorisationform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="benefit_to_society",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="contributing_org_name",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="contribution_amount_or_percent",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="estimated_accommodation",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="estimated_entrance_ticket",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="estimated_subsistence",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="estimated_travel",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="event_date",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="event_title",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="objective",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="other_org_contributing",
        ),
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="total_estimated_cost",
        ),
        migrations.AddField(
            model_name="preauthorisationform",
            name="estimated_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="preauthorisationform",
            name="expense_reason",
            field=models.TextField(default=""),
        ),
    ]
