# Generated by Django 4.1.3 on 2026-04-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_remove_preauthorisationform_benefit_to_society_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preauthorisationform",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="preauthorisationform",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preauthorisationform",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
